services:
  backend:
    build: ./hapi-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
  frontend:
    build: ./react-app
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    working_dir: /app
    depends_on:
      - backend