services:
  backend:
    build: ./hapi-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
  frontend:
    build: ./react-app
    ports:
      - "80:80"
    depends_on:
      - backend
